name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - argh=0.26.2=py38_1001
  - astroid=2.4.1=py38h32f6830_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - colorama=0.4.3=py_0
  - decorator=4.4.2=py_0
  - docopt=0.6.2=py_1
  - ipython=7.14.0=py38h32f6830_0
  - ipython_genutils=0.2.0=py_1
  - isort=4.3.21=py38h32f6830_1
  - jedi=0.17.0=py38h32f6830_0
  - lazy-object-proxy=1.4.3=py38h1e0a361_2
  - ld_impl_linux-64=2.34=h53a641e_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgomp=9.2.0=h24d8f2e_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - mccabe=0.6.1=py_1
  - more-itertools=8.2.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - openssl=1.1.1g=h516909a_0
  - packaging=20.1=py_0
  - parso=0.7.0=pyh9f0ad1d_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pip=20.1=pyh9f0ad1d_0
  - pluggy=0.13.1=py38h32f6830_1
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - py=1.8.1=py_0
  - pygments=2.6.1=py_0
  - pylint=2.5.2=py38h32f6830_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pytest=5.4.2=py38h32f6830_0
  - pytest-watch=4.1.0=py38_1000
  - python=3.8.2=he5300dc_7_cpython
  - python_abi=3.8=1_cp38
  - pyyaml=5.3.1=py38h1e0a361_0
  - readline=8.0=hf8c457e_0
  - setuptools=46.2.0=py38h32f6830_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.0=py_0
  - traitlets=4.3.3=py38h32f6830_1
  - watchdog=0.10.2=py38_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - wrapt=1.11.2=py38h1e0a361_0
  - xz=5.2.5=h516909a_0
  - yaml=0.2.4=h516909a_0
  - zlib=1.2.11=h516909a_1006

